#spring:
#  jpa:
#    hibernate:
#      ddl-auto: update
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    show-sql: true
#  datasource:
#    url: "jdbc:postgresql://localhost:5432/MTM"
#    username: ${db_username}
#    password: ${db_password}
spring:
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  datasource:
    url: "jdbc:h2:./db"
    username: sa
    password: password
  h2:
    console.enabled: true
  liquibase:
    change-log: classpath:db/liquibase-changelog.yml
constants:
  jwt:
    issuer: Forest
    expireSec: 1800
    clockSkewSec: 120
    secretKey: ${jwt_key}
  tmdb:
    baseUrl: https://api.themoviedb.org/3
    tmdbKey: ${tmdb_key}
    searchMovieAPI: /search/movie
logging:
  level:
    root: INFO
    com.forest.mytopmovies: DEBUG
  file:
    name: log/MTM.log
  logback:
    rollingpolicy:
      file-name-pattern: log/MTM-%d{dd-MM-yyyy}.%i.log