spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  datasource:
    url: "jdbc:postgresql://localhost:5432/MTM"
    username: ${db_username}
    password: ${db_password}
constants:
  jwt:
    issuer: Forest
    expireSec: 1800
    clockSkewSec: 120
    secretKey: ${jwt_key}
