name: Java CI Test with Maven

on:
  push:
    branches: [ feature/MTM-26-deployment ]
  pull_request:
    branches: [ feature/MTM-26-deployment ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Unit Test
      run: mvn clean test
    - name: Integration Test
      run: mvn clean verify
